version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.4.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.4.x)"
    milestone: 32
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-open-service-broker-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.3.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.3.x)"
    milestone: 31
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-open-service-broker-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.2.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.2.x)"
    milestone: 30
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-open-service-broker-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "2.1.x"
    schedule:
      interval: daily
    commit-message:
      prefix: "(2.1.x)"
    milestone: 29
    labels:
      - dependencies
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-starter-open-service-broker"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-open-service-broker-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
