image:https://build.spring.io/plugins/servlet/wittified/build-status/CLOUD-SCAB["Bamboo", link="https://build.spring.io/browse/CLOUD-SCAB"]
image:https://circleci.com/gh/spring-cloud/spring-cloud-app-broker.svg?style=svg["CircleCI", link="https://circleci.com/gh/spring-cloud/spring-cloud-app-broker"]
image:https://api.codacy.com/project/badge/Grade/72dc83489cb84106bcca9d0d20430622["Codacy code quality", link="https://www.codacy.com/app/scottfrederick/spring-cloud-app-broker?utm_source=github.com&utm_medium=referral&utm_content=spring-cloud/spring-cloud-app-broker&utm_campaign=Badge_Grade"]
image:https://codecov.io/gh/spring-cloud/spring-cloud-app-broker/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/spring-cloud/spring-cloud-app-broker/branch/master"]

== Spring Cloud App Broker

Spring Cloud App Broker is a framework for building Spring Boot applications that implement the Open Service Broker API to deploy applications to a platform.

The Open Service Broker API project allows developers to deliver services to applications running within cloud native platforms such as Cloud Foundry, Kubernetes, and OpenShift.
Spring Cloud App Broker provides a framework based on Spring Boot that enables you to quickly create a service broker that deploys applications and services to the platform when managed services are provisioned.

Currently Cloud Foundry is supported as a target platform for service instance backing applications and services.

=== Getting Started

See the https://spring.io/projects/spring-cloud-app-broker/[project site] and https://docs.spring.io/spring-cloud-app-broker/docs/current/reference/html5/[reference documentation] to get started building a service broker using this framework.

=== Compatibility

==== 1.1.x

* https://projects.spring.io/spring-framework/[Spring Framework] 5.2.x
* https://projects.spring.io/spring-boot/[Spring Boot] 2.2.x
* https://github.com/cloudfoundry/cf-java-client/[Cloud Foundry Java Client] 4.x
* https://github.com/reactor/[Reactor] 3.3.x
* https://spring.io/projects/spring-cloud-open-service-broker/[Spring Cloud Open Service Broker] 3.1.x
* https://github.com/openservicebrokerapi/servicebroker/tree/v2.15/[Open Service Broker API] 2.15

==== 1.0.x

* https://projects.spring.io/spring-framework/[Spring Framework] 5.1.x
* https://projects.spring.io/spring-boot/[Spring Boot] 2.1.x
* https://github.com/cloudfoundry/cf-java-client/[Cloud Foundry Java Client] 3.x
* https://github.com/reactor/[Reactor] 3.2.x
* https://spring.io/projects/spring-cloud-open-service-broker/[Spring Cloud Open Service Broker] 3.0.x
* https://github.com/openservicebrokerapi/servicebroker/tree/v2.14/[Open Service Broker API] 2.14

=== Build

This project requires Java 8 at a minimum.

The project is built with Gradle.
The https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper] allows you to build the project on multiple platforms and even if you do not have Gradle installed; run it in place of the `gradle` command (as `./gradlew`) from the root of the main project directory.

=== Getting Started

See the https://spring.io/projects/spring-cloud-app-broker/[project site] and https://docs.spring.io/spring-cloud-app-broker/docs/current/reference/html5/[reference documentation] to get started building a service broker using this framework.

Take a look at this https://spring.io/blog/2019/05/30/introducing-spring-cloud-app-broker[introduction blog post] and to our https://github.com/spring-cloud-samples/spring-cloud-app-broker-samples[sample apps].


==== Compile the project and run tests

    ./gradlew build
