= Spring Cloud App Broker Acceptance Tests

== Running locally

=== Compile the project

    $ ./gradlew build

=== Running the tests

== Running

The tests require the following properties to be set:

* `tests.testBrokerAppPath` - The path to the test broker jar (eg. /spring-cloud-app-broker-integration-tests/build/libs/spring-cloud-app-broker-integration-tests.jar).
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.api-host` - The CF API host where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.api-port` - The CF API port where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.username` - The CF API username where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.password` - The CF API password where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.default-org` - The CF organization where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.default-space` - The CF space where the tests are going to run.
* `spring.cloud.appbroker.acceptance-test.cloudfoundry.skip-ssl-validation` - If SSL validation should be skipped.

These properties can be set with `-D` system properties on the gradle command line.

Also, the flag acceptanceTests must be provided as `-PacceptanceTests`.

[source,bash]
----
$ ./gradlew test -PacceptanceTests \
 -Dtests.testBrokerAppPath=/path/to/broker.jar \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.api-host=api.cf.my.cf.io  \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.api-port=443 \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.username=admin \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.password=password \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.default-org=test \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.default-space=development \
 -Dspring.cloud.appbroker.acceptance-test.cloudfoundry.skip-ssl-validation=true
----