---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/app-broker-ci
    username: ((corporate-harbor-robot-account.username))
    password: ((corporate-harbor-robot-account.password))
    tag: ((ci-image-tag))
inputs:
  - name: git-repo
  - name: cf-environment
run:
  path: ci/scripts/acceptance-tests.sh
  dir: git-repo
params:
  METADATA_FILE: ../cf-environment/metadata
