---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/app-broker-ci
    username: ((corporate-harbor-robot-account.username))
    password: ((corporate-harbor-robot-account.password))
    tag: ((branch))
inputs:
  - name: git-repo
  - name: toolsmith-env
run:
  path: ci/scripts/acceptance-tests.sh
  dir: git-repo
params:
  TOOLSMITH_ENV_INPUT: ../toolsmith-env
  DEFAULT_ORG: ((acceptance-test-default-org))
  DEFAULT_SPACE: ((acceptance-test-default-space))
  SKIP_SSL_VALIDATION: ((acceptance-test-skip-ssl-validation))
  ONLY_SHOW_STANDARD_STREAMS_ON_TEST_FAILURE: true
