---
aliases:
  - &slack-success-notification
    put: alert
    params:
      icon_emoji: ":concourse:"
      username: concourse
      channel: ((ab-slack-success-channel))
      text: "`$BUILD_PIPELINE_NAME` pipeline has succeeded with build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME>!"

  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal-1252:"
      username: concourse
      channel: ((ab-slack-failure-channel))
      text: "<!here> Build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME> of job `$BUILD_JOB_NAME` in the `$BUILD_PIPELINE_NAME` pipeline has failed!"

  - pull-request-status-updates:
      - &pull-request-pending
        put: update-status
        resource: pull-request
        get_params: { skip_download: true }
        inputs: detect
        params: &pull-request-pending-context
          path: scg
          status: pending
          base_context: ((pipeline-name))

      - &pull-request-success
        put: update-status
        resource: pull-request
        get_params: { skip_download: true }
        inputs: detect
        params: &pull-request-success-context
          path: scg
          status: success
          base_context: ((pipeline-name))

      - &pull-request-failure
        put: update-status
        resource: pull-request
        get_params: { skip_download: true }
        inputs: detect
        params: &pull-request-failure-context
          path: scg
          status: failure
          base_context: ((pipeline-name))

      - &pull-request-error
        put: update-status
        resource: pull-request
        get_params: { skip_download: true }
        inputs: detect
        params: &pull-request-error-context
          path: scg
          status: error
          base_context: ((pipeline-name))

  - build:
      - &mark-build-pending
        <<: *pull-request-pending
        params:
          context: build
          <<: *pull-request-pending-context

      - &mark-build-successful
        <<: *pull-request-success
        params:
          context: build
          <<: *pull-request-success-context

      - &mark-build-errored
        <<: *pull-request-error
        params:
          context: build
          <<: *pull-request-error-context

      - &mark-build-failed
        <<: *pull-request-failure
        params:
          context: build
          <<: *pull-request-failure-context

  - acceptance-tests:
      - &mark-acceptance-test-jobs-checks-pending
        <<: *pull-request-pending
        params:
          context: acceptance-tests
          <<: *pull-request-pending-context

      - &mark-acceptance-tests-successful
        <<: *pull-request-success
        params:
          context: acceptance-tests
          <<: *pull-request-success-context

      - &mark-acceptance-tests-errored
        <<: *pull-request-error
        params:
          context: acceptance-tests
          <<: *pull-request-error-context

      - &mark-acceptance-tests-failed
        <<: *pull-request-failure
        params:
          context: acceptance-tests
          <<: *pull-request-failure-context

jobs:
  - name: build
    plan:
      - get: pull-request
        trigger: true
        version: every
      - *mark-build-pending
      - task: build-project
        timeout: 1h30m
        file: pull-request/ci/tasks/build-project.yml
        input_mapping:
          git-repo: pull-request
        vars:
          ci-image-tag: ((ci-image-tag))
    on_success: *mark-build-successful
    on_failure: *mark-build-failed
    on_abort: *mark-build-errored
    on_error: *mark-build-errored

  - name: run-acceptance-tests
    serial: true
    plan:
      - in_parallel:
          - get: pull-request
            passed: [ build ]
            trigger: true
          - put: cf-environment
            params:
              action: create
              duration: 6h
              resource: cf-environment
            timeout: 6h
      - *mark-acceptance-test-jobs-checks-pending
      - task: acceptance-tests
        file: pull-request/ci/tasks/acceptance-tests.yml
        vars:
          ci-image-tag: ((ci-image-tag))
        input_mapping:
          git-repo: pull-request
    on_success:
      in_parallel:
        - *slack-success-notification
        - *mark-acceptance-tests-successful
        - put: cf-environment
          params:
            action: release
            resource: cf-environment
    on_failure:
      in_parallel:
        - *slack-failure-notification
        - *mark-acceptance-tests-failed
    on_error:
      in_parallel:
        - *slack-failure-notification
        - *mark-acceptance-tests-errored
    on_abort: *mark-acceptance-tests-errored

resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/teliaoss/github-pr-resource
      tag: latest

  - name: slack-notification
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/cfcommunity/slack-notification-resource
      tag: latest

  - name: shepherd
    type: registry-image
    source:
      repository: ((shepherd-image-repository))/shepherd-268822/shepherd2/concourse-resource
      tag: v1

resources:
  - name: pull-request
    type: pull-request
    version:
      pr: ((pr.number))
      commit: ((pr.commit))
    source:
      repository: ((app-broker-pr-github-pull-requests-repo))
      access_token: ((app-broker-pr-github-pull-requests-access-token))
      base_branch: ((pr.base-branch))
      disable_forks: true
      required_review_approvals: 1

  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))

  - name: cf-environment
    type: shepherd
    source:
      url: https://v2.shepherd.run
      service-account-key: ((shepherd-service-account-key))
      lease:
        namespace: spring-cloud-app-broker
        pool:
          namespace: official
          name: cfd
      compatibility-mode: environments-app
