= Spring Cloud App Broker Sample Project

== Running locally

=== Compile the project

    $ ./gradlew build

=== Configure a Cloud Foundry target

Set the following environment variables to specify a valid Cloud Foundry environment that service instance backing applications will be deployed to:

* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_APIHOST
* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_APIPORT
* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_USERNAME
* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_PASSWORD
* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_DEFAULTORG
* SPRING_CLOUD_APPBROKER_DEPLOYER_CLOUDFOUNDRY_DEFAULTSPACE

=== Run the application

    $ SPRING_PROFILES_ACTIVE=local ./gradlew bootRun

=== Install an Open Service Broker API CLI

See https://github.com/starkandwayne/eden[Eden Open Service Broker API CLI]

=== Test the service broker

```
   $ eden catalog --url=http://localhost:8080 --client=test --client-secret=test
   Service Name  Plan Name  Description
   example       standard   A simple plan

   1 services

   $ eden provision -i test-instance --url=http://localhost:8080 --client=test --client-secret=test -s example-service -p simple-plan
   provision:   example/standard - name: test-instance
   provision:   done
```

Inspect the org and space to verify that an application named `broker-sample-app` was created.

```
   $ eden deprovision -i test-instance
   deprovision: example/standard - guid: 95b12624-9128-4cad-91cc-1a19b08e8a64
   deprovision: done
```

Inspect the org and space to verify that the application `broker-sample-app` was deleted.

== Recording a new scenario

- Ensure the live Cloud Foundry environment has an organization named `test` that contains a space named `development`
- Create a new test case with a test method
- Create a new recording folder in `/src/test/resources/recordings/{test_name}/mappings` using the name of the
test method
- Set the following environment variables

* WIREMOCK_RECORD=true
* WIREMOCK_CLOUDFOUNDRY_APIURL=https://api.example.com
* WIREMOCK_CLOUDFOUNDRY_ACCESSTOKEN={access token value}

where `{access token value}` is a valid UAA access token that can be used to authenticate to the Cloud Foundry API;
this can easily be retrieved using `cf oauth-token` with a user that has access to the `test` organization and `development` space

- Run the test method

