= Spring Cloud App Broker Sample Project

== Running locally

=== Compile the project

    $ ./gradlew build

=== Configure a Cloud Foundry target

Set the following environment variables to specify a valid Cloud Foundry environment that service instance backing applications will be deployed to:

* SPRING_CLOUD_APPBROKER_CF_APIHOST
* SPRING_CLOUD_APPBROKER_CF_APIPORT
* SPRING_CLOUD_APPBROKER_CF_USERNAME
* SPRING_CLOUD_APPBROKER_CF_PASSWORD
* SPRING_CLOUD_APPBROKER_CF_DEFAULTORG
* SPRING_CLOUD_APPBROKER_CF_DEFAULTSPACE

=== Run the application

    $ SPRING_PROFILES_ACTIVE=local ./gradlew bootRun

=== Install an Open Service Broker API CLI

See https://github.com/starkandwayne/eden[Eden Open Service Broker API CLI]

=== Test the service broker

```
   $ eden catalog --url=http://localhost:8080 --client=test --client-secret=test
   Service Name  Plan Name  Description
   example       standard   A simple plan

   1 services

   $ eden provision -i test-instance --url=http://localhost:8080 --client=test --client-secret=test -s example-service -p simple-plan
   provision:   example/standard - name: test-instance
   provision:   done
```

Inspect the org and space to verify that an application named `broker-sample-app` was created.

```
   $ eden deprovision -i test-instance
   deprovision: example/standard - guid: 95b12624-9128-4cad-91cc-1a19b08e8a64
   deprovision: done
```

Inspect the org and space to verify that the application `broker-sample-app` was deleted.

== Recording a new scenario

- Create a new recording folder in `/src/test/resources/recordings/{test_name}/mappings`
- In `WiremockComponentTest` replace the `ACCESS_TOKEN` with a real one:
```
curl https://login.cf.{my_env}/oauth/token -X POST -k -d "client_id=cf&client_secret=&grant_type=password&password={my_admin_password}&username=admin" | jq .access_token
```
- In `WiremockComponentTest` in `startWiremock` add before `wiremockServer.start();`:
```
		wiremockServer.startRecording(
			recordSpec()
				.forTarget("https://api.cf.{my_env}")
		);
```
- In `WiremockComponentTest` in `stopWiremock` add before `wiremockServer.stop();`:
```
		WireMock.stopRecording();
```
