= Spring Cloud App Broker Sample Project

== Running locally

=== Compile the project

    $ ./gradlew build

=== Configure a Cloud Foundry target

Set the following environment variables to specify a valid Cloud Foundry environment that service instance backing applications will be deployed to:

* SPRING_CLOUD_APPBROKER_CF_APIHOST
* SPRING_CLOUD_APPBROKER_CF_APIPORT
* SPRING_CLOUD_APPBROKER_CF_USERNAME
* SPRING_CLOUD_APPBROKER_CF_PASSWORD
* SPRING_CLOUD_APPBROKER_CF_DEFAULTORG
* SPRING_CLOUD_APPBROKER_CF_DEFAULTSPACE

=== Run the application

    $ java -jar build/libs/spring-cloud-app-broker-sample-1.0.0.BUILD-SNAPSHOT.jar

=== Install an Open Service Broker API CLI

See https://github.com/starkandwayne/eden[Eden Open Service Broker API CLI]

=== Test the service broker

```
    $ eden catalog --url=http://localhost:8080 --client=test --client-secret=test
    Service Name  Plan Name  Description
    example       standard   A simple plan

    1 services

    $ eden provision --url=http://localhost:8080 --client=test --client-secret=test -i test-instance -s example-service -p simple-plan
    provision:   example/standard - name: test-instance
    provision:   done
```

Inspect the org and space to verify that an application named `broker-sample-app` was created.

