name: Java 17 baseline build

on:
  push:
    branches: [ 2.5.x, 2.4.x, 2.3.x, 2.2.x, 2.1.x ]
  pull_request:
    branches: [ 2.5.x, 2.4.x, 2.3.x, 2.2.x, 2.1.x ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '17', '21' ]
    uses: ./.github/workflows/gradle-build.yml
    with:
      java-version: ${{ matrix.java }}
